###use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 10000
}

###cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "dfc37738cd8e4ac79034ccc25c74bc77",
  "accountNumber": "1000000000",
  "amount": 10000
}

